// Generated by CoffeeScript 1.6.3
(function() {
  var data, svg, textField, updateData;

  svg = d3.select("#vis1").append("svg");

  svg.attr({
    width: 600,
    height: 400
  });

  textField = d3.select("body").append("div").text("value");

  d3.select("body").append("button").text("shuffle").on({
    "click": function() {
      return updateData();
    }
  });

  d3.select("body").append("button").text("change scale").on({
    "click": function() {
      return changeScale();
    }
  });

  d3.select("body").append("button").text("swap").on({
    "click": function() {
      return swapX();
    }
  });

  data = [];

  updateData = function() {
    var dataSize, i, _i, _results;
    dataSize = Math.random() * 50 + 50;
    _results = [];
    for (i = _i = 0; 0 <= dataSize ? _i <= dataSize : _i >= dataSize; i = 0 <= dataSize ? ++_i : --_i) {
      _results.push(data[i] = {
        pos: i,
        value: Math.random() * 9999 + 1
      });
    }
    return _results;
  };

  updateData();

  console.log(data);

}).call(this);

/*
//@ sourceMappingURL=scaleVis.map
*/
